[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/"
]
auto_generate_artifacts = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC}"

[etherscan]
optimism_sepolia = { key = "${ETHERSCAN_API_KEY}" }
