[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC}"

[etherscan]
optimism_sepolia = { key = "${ETHERSCAN_API_KEY}" } 